### PR TITLE
Aodn aims ctd

### PR DESCRIPTION
**Pull request by bpasquer**

### CODE REVIEW

**Comment by bpasquer** [comment]
will you have a chance to look at this before you go @lbesnard?

**Comment by lbesnard** [comment]
@bpasquer did you put a PR as well for the harvester ? can't find it

**Comment by ggalibert** [comment]
@atkinsn we need to publish this record to production : https://catalogue-rc.aodn.org.au/geonetwork/srv/eng/metadata.show?uuid=46070c25-5f76-449a-b08a-e2ffe15d8085

@xhoenner this PR should ready for review since the relevant harvester is running in rc and prod.

**Comment by smancini** [comment]
We should only publish this record in RC for now.
I will contact AIMS and show them what we did with their dataset and sk for their agreement to publish it into portal 1-2-3

**Comment by ggalibert** [comment]
We can publish it but with limited visibility to the outside world. So that Nagios says green for the harvester.

**Comment by xhoenner** [comment]
I get a HTTP Status 500 error when previewing the aodn_aims_ctd_map layer. Here's below a copy of the log from catalina.out. In the style used for this _map layer, there's a reference to a column called 'STATION_NAME' whereas the actual database table only has 'Station'

screen shot 2015-08-06 at 1 26 08 pm

**Pull request merged**
