### PR TITLE
import filters from portal to geoserver

### PR DESCRIPTION
**Pull request by danfruehauf**
*** DO NOT MERGE YET ***

This is the filter configuration from portal-123 imported into geoserver. It has been imported in an automatic way.

### CODE REVIEW

**Comment by danfruehauf** [comment]
@julian1 Whenever you're ready - this can go in.

**Comment by danfruehauf** [comment]
@julian1 Hold on, this actually doesn't work anymore...

**Comment by julian1** [comment]
The filter configuation edit, serialization, deserialization steps work in the extension. Whether this branch of the config works is a secondary issue. I am happy to fix it later.

**Comment by danfruehauf** [comment]
Scratch that, works perfectly, I was on the wrong branch.

**Comment by danfruehauf** [comment]
I just updated the filters as taken from portal. One problem though - the `visualised` and `excludeFromDownload` flags are not set properly. POs will have to revisit those and reconfigure them.

**Comment by danfruehauf** [comment]
A call to the data team:
@bpasquer @ggalibert @mhidas @smancini @lbesnard @xhoenner 

Please have a look at those filters and see if there are any filters that should not be `visualised` or should have `excludeFromDownload`. If you notice anything now - good. If not, things /should/ still work once we start using the filter probing plugin.

For example:
I could notice for instance that `juld` in `argo_profile_layer_map` should not be visualised, but only included in download. However getting the portal config it says it should be visualised.

**Comment by bpasquer** [comment]
OK, Checked . And I’ve got nothing to complain about
On 24 Feb 2015, at 11:44 am, Dan Fruehauf <notifications@github.com<mailto:notifications@github.com>> wrote:


A call to the data team:
@bpasquer<https://github.com/bpasquer> @ggalibert<https://github.com/ggalibert> @mhidas<https://github.com/mhidas> @smancini<https://github.com/smancini> @lbesnard<https://github.com/lbesnard> @xhoenner<https://github.com/xhoenner>

Please have a look at those filters and see if there are any filters that should not be visualised or should have excludeFromDownload. If you notice anything now - good. If not, things /should/ still work once we start using the filter probing plugin.

For example:
I could notice for instance that juld in argo_profile_layer_map should not be visualised, but only included in download. However getting the portal config it says it should be visualised.

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/geoserver-config/pull/230#issuecomment-75675490>.

Dr. Benedicte Pasquer - Project Officer
Monday - Thursday
IMOS e-Marine Information Infrastructure
University of Tasmania
Ph: +61 3 6226 1927












University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Pull request merged**
