### PR TITLE
Asset map showing the location of IMOS assets

### PR DESCRIPTION
**Pull request by xhoenner**

### CODE REVIEW

**Comment by xhoenner** [comment]
@danfruehauf this PR's been merged for three days but I can't find this layer on geoserver-rc, any idea?

**Comment by lbesnard** [comment]
prob cause the branche wan't merged to production

**Comment by danfruehauf** [comment]
@lbesnard RC takes the master branch

**Comment by danfruehauf** [comment]
@xhoenner I can see it ran last time almost 3 days ago, that is because it runs only if there are changes in the chef repo. Usually there are. I'll set it to run periodically too.

**Comment by xhoenner** [comment]
great, thanks for that @danfruehauf!

**Pull request merged**
