### PR TITLE
Argo

### PR DESCRIPTION
**Pull request by lbesnard**
* modify layer names. Native name(similar to the table name) was different from
   the 'name' found in geoserver. This made impossible to know which layer was
   linked to which table. Also because of this mismatch, updating layers became
   buggy on local vagrant. done expect for argo_profile_data (see next point)
 * argo_profile_data has a different native name (view name in db). TO be more
   consistent it should have been named profile_download. However this is not
   consistent with the others JNDI 's stores. In the future, the argo harvester
   will have to update these view names.
 * delete store JNDI_argo_data which was the store used by aodn portal.
 * moved filters which were in JNDI_argo_data (deleted store)
 * the layer argo_aggregation was removed (used by aodn portal)
 * the metadata records ON 123 and MEST (used by aodn portal) will need to be
   updated with the new layer names. WFS, WMS and BOADAAC XML entries need to be
   modified prior testing, otherwise this won't work.

### CODE REVIEW

**Comment by lbesnard** [comment]
__IMPORTANT__ : to do in catalogue RC
> WFS, WMS and BOADAAC XML entries need to be modified prior testing, otherwise this won't work.

this was tested on the po box. no problem.

**Comment by lbesnard** [comment]
in ref of https://github.com/aodn/geoserver-config/pull/225 

This PR didn't work at the time, but actually should have worked. Only reason was that the metadata records should have been modified to get the new layer names, but forgot about it because this PR took so much time to be touched.

**Comment by ggalibert** [comment]
1-WFS and WMS getCapabilities worked fine.

2-Titles and names of layer are not consistently documented. See screenshots below :
a- Some names have argo in them, some don't.
b- Some titles have underscores, some don't.

argo_layers

I understand your point with consistency with the table/view names in the db but there as well it would be good to adopt consistent practices at some stage...

argo_tables_views

3-Layer preview:
a- The following layers don't show anything : profile_param_calibration, profile_history, argo_profile_data, profile_params, argo_float_abos_aodn_vw, profile_measurements, platform_params, profile_general, platform_metadata, platform_nominal_cycle
b- argo_float and argo_float_oxygen_aodn_vw content FTL includes something like :
```
Max Extent: -47.742N 179.3E -57.498S -178.463W 
```
Adding N or S or E or W just after some coordinate value is one standard to express geographic coordinates with positive values only. Using signed coordinate values is another standard (and assumes positive North, positive East). Combining both is not standard!

I suggest you use the portal practice so that it is represented with something like this :
```
Max Extent: 
N:-47.742 S:-57.498
W:-178.463 E:179.3
```
Also, putting latitude and longitude together is easier to read, with North or West most coordinate first.

c- argo_float and argo_float_oxygen_aodn_vw "Add argo track to map" link is not working.
d- argo_float and argo_float_oxygen_aodn_vw "Get argo track as KML" link is not working.
e- argo_float_oxygen_aodn_vw "History" and "Latest Profile Graphs" links are failing.

**Comment by lbesnard** [comment]
thanks @ggalibert for reviewing. You had a fair point about consistency, and I was always a bit stuck with taking over this harvester, as it was dealing with both the old AODN portal and 123. As it was the first ever harvester, I think all the different views were added to geoserver, even though they weren't used neither by wms or wfs. I guess I wasn't sure if they were used by the AODN portal, so I didn't want to remove them.

Anyway, if you check on the current AODN portal, none of the argo layer currently works. So it's time to cleaned out everything. I just put another commit which only keeps:
 * argo_profile_data
 * argo_profile_map

so all your points in section 3) are now solved.

> 2-Titles and names of layer are not consistently documented. See screenshots below :

cleaned too


Next step is to clean the harvester, makes it easy now I know nothing is used by the AODN portal. Many views can disappear/be renamed


Let me know if you're happy with it, and I'll merge the 2 commits into 1.

thanks

**Comment by ggalibert** [comment]
Looks good to me.

**Comment by lbesnard** [comment]
@ggalibert , when happy, can you put this please on RC and prod later on ? cheers

**Comment by ggalibert** [comment]
@lbesnard let me know when you're happy to have it in prod.

**Comment by lbesnard** [comment]
@ggalibert if you can do it before 5pm, would be amazing, it will get automatically deploy to 123. I'll just have to change the record at 5pm/

cheers

**Comment by ggalibert** [comment]
done

**Comment by lbesnard** [comment]
actually was not merged to prod branch, so I guess this will have to be sorted out tomorrow

**Comment by ggalibert** [comment]
Should be sorted now.

**Pull request merged**
