### PR TITLE
fix jndi store names

### PR DESCRIPTION
**Pull request by danfruehauf**
* remove `dbprod_harvest_` from store names

Merge after #236

### CODE REVIEW

**Comment by jkburges** [comment]
Do any services depend on layers being in a certain datastore (e.g. the portal)?

**Comment by danfruehauf** [comment]
@jkburges Na, it was just ugly. I think it's up to one of the POs to merge this. It's just following some sort of standard...

**Comment by danfruehauf** [comment]
Any buyers for that PR?

**Comment by danfruehauf** [comment]
*ping*

**Comment by julian1** [comment]
Wanted this for ages.

**Pull request merged**
