### PR TITLE
Add test.sh test entry point for Jenkins

### PR DESCRIPTION
**Pull request by lwgordonimos**

### CODE REVIEW

**Comment by akashisama** [comment]
Hmm it's trying to test the  xml files in  the .git directory... The original script in the old jenkins doesn't...

**Comment by lwgordonimos** [comment]
I don't see how, since I didn't change the find command at all? Is it breaking now on new Jenkins?

**Comment by lwgordonimos** [comment]
And there aren't any XML files in the .git directory for me anyway?

**Comment by lwgordonimos** [comment]
@akashisama try again now. I've excluded .git just in case it hits problems (since it never makes sense to do anything with the directory anyway).

**Comment by akashisama** [comment]
Mmm contents of .git would depend on what sort of stuff you've done in the past on the repo. It was picking up files like ./.git/logs/refs/heads/add_templates.xml

Changing the retval assignment back to echo -n $tmp_output 2| wc -l fixed it for me but don't know enough about those echo arguments to know why...

I think excluding the .git directory is a good solution so will merge if your happy with it.

**Comment by lwgordonimos** [comment]
The previous echo command was incorrect, because if there was exactly one error, it didn't pick it up anyway. `echo -n` omits the newline... wc is specifically counting newline characters.

I assume the `-n` was added because without it, even an empty string is a "line" because of the implicit newline.

```bash
# echo an empty string with a newline appended
echo | wc -l
1
```
Unfortunately the side effect was this:

```bash
$ echo -n "this will echo with no newline character, so isn't considered a line" | wc -l
0
```

I think this is right to merge now. Will hopefully have more sophisticated tests in future anyway, but this will retain current tests.

**Comment by mhidas** [comment]
Are these changes ready to go to prod? They were merged over a month ago, but hadn't even been deployed to RC.
I just ran the [geoserver-config](https://jenkins.aodn.org.au/view/geoserver_config/) pipeline on Jenkins, so this PR is now part of version 0.1.9 ([changes from previous](https://github.com/aodn/geoserver-config/compare/0.1.8...0.1.9)) and will be on RC soon.
I'd like to see this deployed to prod asap as it fixes a [broken portal collection](https://github.com/aodn/issues/issues/705).

**Pull request merged**
