### PR TITLE
Adding multiple time config for srs_sst

### PR DESCRIPTION
**Pull request by bhasin85**
Related to [156](https://github.com/aodn/geoserver-build/pull/156)

### CODE REVIEW

**Comment by ggalibert** [comment]
What about adding entries for:
* geospatial_lat_min / max
* geospatial_lon_min / max

?

These attributes too will need to be updated.

**Comment by jonescc** [comment]
@ggalibert - we are waiting for a decision on https://github.com/aodn/go-go-duck/issues/124#issuecomment-238460400 before changing this from the way it works at the moment.

**Comment by ggalibert** [comment]
So why have you already taken a decision on how to deal with the temporal attributes then?

**Comment by jonescc** [comment]
Note that this just applies to srs_sst - defaults for othe collections are specified at https://github.com/aodn/geoserver-config/blob/master/wps/gogoduck.xml

**Comment by jonescc** [comment]
For the moment, we are retaining previous behaviour with regard to updating netcdf attributes so that we can fix two serious production issues https://github.com/aodn/aodn-portal/issues/2257 and https://github.com/aodn/aodn-portal/issues/2252

**Pull request merged**
