### PR TITLE
Add file size limit of approx 20GB per job

### PR DESCRIPTION
**Pull request by anguss00**

### CODE REVIEW

**Comment by jonescc** [comment]
Thats not very much - srs_oc has files that are around 1Gb

**Comment by anguss00** [comment]
Yeah, the estimate may be a bit conservative... What do you think should be the number @jonescc?

**Comment by anguss00** [comment]
Changed!

**Comment by julian1** [comment]
what's the size of the /mnt/ebs partition?

**Comment by anguss00** [comment]
At the moment, 160GB, @pblain would like to double it if possible

**Comment by anguss00** [comment]
Closing as this should be managed in chef. My bad

**Comment by julian1** [comment]
I'm wondering if the xml file should be changed to a template file in this repo, rather than in the chef repo.  

Otherwise it becomes very opaque for someone wanting to manually configure a geoserver instance - since the configuration is spread out into multiple repos. 

If it were maintained as a template here, then presumably Geoserver would report an immediate error  - and it would be obvious what needs to change to get it running.

Really not sure though. We don't currently do this for other config - such as sensitive credentials also maintained in this repo .

**Pull request closed without merging**
