### PR TITLE
update temporal filters to UTC time

### PR DESCRIPTION
**Pull request by leonardolaiolo**

### CODE REVIEW

**Comment by mhidas** [comment]
@leonardolaiolo I just noticed [nrs_depth_binned_ctd_data](https://github.com/aodn/geoserver-config/tree/master/workspaces/imos/JNDI_imos_bgc_db/nrs_depth_binned_ctd_data) is missing filters. Could you please add the filters for that too?

**Comment by mhidas** [comment]
Actually, we may need to also add the `Project` column to the CTD data layer, otherwise that filter won't work.

**Comment by leonardolaiolo** [comment]
Last commit to add [filters for nrs_depth_binned_ctd_data](https://github.com/aodn/geoserver-config/pull/732/commits/c6288e90eba2709da4b5306e9241be553897e992) reflects changes consistently in https://github.com/aodn/public-schema/pull/33 made in [this commit](https://github.com/aodn/public-schema/pull/33/commits/98f64e2ba5a6e974a25bd7316e3a0b10c88db8e5). Remember to update config file once the 2 PR are merged (`SampleDate_Local` --> `SampleDate_UTC` in all metadata sections)

**Comment by mhidas** [comment]
> Remember to update config file once the 2 PR are merged (`SampleDate_Local` --> `SampleDate_UTC` in all metadata sections)

Good thinking!

**Review by mhidas — APPROVED** [review]

**Pull request merged**
