### PR TITLE
Fix content.ftl for anmn_nrs_rt_wave_timeseries_map

### PR DESCRIPTION
**Pull request by mhidas**
Fixes https://github.com/aodn/content/issues/326

(Also removed the arbitrary limit of displaying only 5 features. This layer only has a handful a features all up, and there are no more coming in.)

### CODE REVIEW

**Comment by jonescc** [comment]
Works OK in geoserver-rc - I'll leave it to the someone else to merge to prod as I'm not sure what the procedure is there.

**Comment by mhidas** [comment]
There's a Jenkins pipeline `geoserver_config_prod_merge` which does this, which we should run regularly, but it's usually forgotten, so changes pile up on master branch without being deployed to prod.

Currently this change sits on top of 4 other commits (excluding merges, see [diff](https://github.com/aodn/geoserver-config/compare/production...master)) from @xhoenner @lbesnard and myself. All my commits are ok to go to prod, but I don't know about the other 3.

**Comment by mhidas** [comment]
Personally I'd like to just hit the merge button and get this in there before we forget about it again for another month or two. However given that most of the POs will be away for the next 2 weeks I'm not sure that's a good idea?

**Comment by jonescc** [comment]
We'd need to know that those other changes had been tested in RC satisfactorily.  Just merging your changes would be safer.

**Comment by lwgordonimos** [comment]
This is a deployment branch, so changes are strongly associated with an imminent deployment. As a result, changes should not be merged into master unless they are a) satisfactorily tested in PO box and b) a matter of *hours* away from being deployed. 

Otherwise this whole "work in progress changes blocking ready to go changes" is going to happen repeatedly.

We should really move those changes to another branch and out of master, and they can be revisited when they are known to be in a deployable state.

**Comment by mhidas** [comment]
For all I know they _might_ be in a deployable state. Like I said, what tends to happen is we merge them to master, test in RC, then forget to do the prod merge. But there have been cases where we needed a change to be on master so we could e.g. demo layers on RC, but not being ready to go to prod yet.

**Comment by jonescc** [comment]
I think the blocking changes are Loz's.  Xavier's changes have been tested (by Xavier and I) and they were fine/fix performance problems with that layer.   So let's move those out and merge.

**Comment by jonescc** [comment]
So if someone can merge https://github.com/aodn/geoserver-config/pull/563 we can get this unblocked and get some fixes into production.

**Pull request merged**
