### PR TITLE
Argo

### PR DESCRIPTION
**Pull request by lbesnard**
* modify layer names. Native name(similar to the table name) was different from
   the 'name' found in geoserver. This made impossible to know which layer was
   linked to which table. Also because of this mismatch, updating layers became
   buggy on local vagrant.
 * delete store JNDI_argo_data which was the data used by 123 ->
 * modified store JNDI_argo which was used by the aodn portal. This store
   used to connect to Legacy_argo which can now be depreciated
 * the layer argo_aggregation was removed (used by aodn portal)
 * ALL layers for portal 123 are now in the JNDI_argo store
 * ALL layers have their 'name' changed to match their 'native_name' and so
   their table name
 * the metadata records ON 123 and MEST (used by aodn portal) will need to be
   updated with the new layer names
 * This PR will need to be deployed FIRST to RC to be tested with the new version
   of the Argo harvester (which needs to be tested as well on RC)

### CODE REVIEW

**Comment by ggalibert** [comment]
Don't merge to production until test in RC is ok.

**Comment by ggalibert** [comment]
@lbesnard these layers should now be visible in Geoserver RC, could you please have a look at them?

**Comment by lbesnard** [comment]
@i'll have a better look tomorrow. but I think something is not working well

**Comment by lbesnard** [comment]
@ggalibert , actually we shouldn't do this anymore. RC isn't testing.
This layer didn't work as expected and was still in the Jenkins geoserver pipeline ready to be pushed to 123. The main problem arrives to following PR's  which have no idea that this can't be merged to prod. And the working PR's shouldn't have to wait for the bad ones to be reverted before being pushed to 123

**Pull request merged**
