### PR TITLE
Set point default style for acorn_newc to fix getCapabilities

### PR DESCRIPTION
**Pull request by anguss00**
Needed to merge geoserver-config into production

### CODE REVIEW

**Comment by ggalibert** [comment]
Not sure I understand this. Was working fine on my po-box.

**Comment by anguss00** [comment]
Yeah it's weird. All I can assume is that there is a style that exists on PO but not on RC. What was the default that's set in PO box?

**Comment by lbesnard** [comment]
It seems like it's easy to break the getCapabilites but still have the layers performing fine on the pobox. That has happened to me a few times

**Comment by ggalibert** [comment]
In the PO box, default style says `generic`. See below:

screenshot from 2018-02-22 15-57-16

**Comment by ggalibert** [comment]
GetCapabilities works on PO box. Anyway, happy to merge this change if that can fix it in RC/prod.

**Pull request merged**
