### PR TITLE
AODN WAVE DM - add DTA waverider to style

### PR DESCRIPTION
**Pull request by lbesnard**
@lwgordonimos running the ``` stackman push_geoserver_config``` ,
The following files got also pushed.:
*  gwc-gs.xml
*  controlflow.properties  

I don't think it affects anything. If so @bpasquer can merge the changes

### CODE REVIEW

**Comment by lwgordonimos** [comment]
@lbesnard these files should be excluded from the PR. These files are config files that get templated during deployment on a per-environment basis, so shouldn't be committed to the shared repository.

**Comment by lbesnard** [comment]
@bpasquer this add a new logo for the buoy with a yellow circle

**Comment by bpasquer** [comment]
@lbesnard waiting for you to remove the abovementioned files from the PR

**Comment by lwgordonimos** [comment]
FYI, they should have been ignored. I've fixed this in a PR in the deployment code, so should be excluded next time you run up a stack and use `stackman push_geoserver_config`.

**Comment by lbesnard** [comment]
@bpasquer I removed the other 2 files

**Pull request merged**
