### PR TITLE
NOAA Drifters - create new style to fix missing hits

### PR DESCRIPTION
**Pull request by lbesnard**
* creation of a big and fat line (50pixels) around the main one with an
   opacity value of 0.01 (fine tuning as small than that, and it doesnt
   work, doesnt make sense but thats how it is). One can now click on a
   track and getfeature info back

### CODE REVIEW

**Comment by lbesnard** [comment]
@smancini hopefully it should be better, happy to demonstrate

**Comment by xhoenner** [comment]
The GetFeatureInfo definitely works a lot better now, but unfortunately this 'big fat line (50 pixels) with an opacity of 0.01' is actually quite visible at the standard resolution over land. See the before and after screenshots.

noaa

**Comment by lbesnard** [comment]
how about now @xhoenner ? I put a white colour, it looks better / perfect

**Comment by pmbohm** [comment]
Fixes https://github.com/aodn/content/issues/188

**Pull request merged**
