### PR TITLE
ANMN NRS LONG TS - new layers

### PR DESCRIPTION
**Pull request by lbesnard**
* one WMS, multi wfs
 * no filtering

### CODE REVIEW

**Comment by lbesnard** [comment]
@smancini no filtering as not available on PO
@atkinsn I don't know if this is for you, but we need to configure the multi WFS
The two WFS are 
anmn_nrs_long_ts_interpolated_data
anmn_nrs_long_ts_original_data

**Comment by atkinsn** [comment]
I can look after that for you @lbesnard

**Comment by atkinsn** [comment]
Done @lbesnard

**Comment by lbesnard** [comment]
@smancini this is ready to be online as soon as this PR is merged

**Pull request merged**
