### PR TITLE
SRS OC: replace old layers with ones from generic timestep harvester/…

### PR DESCRIPTION
**Pull request by lbesnard**
…schema

### CODE REVIEW

**Comment by lbesnard** [comment]
@atkinsn when this is about to be merged, can you modify the robert johnson metadata records so they can point to the new layers names?
srs_oc_contributed_aqua_johnson_1m
srs_oc_contributed_seawifs_johnson_1m
srs_oc_contributed_aqua_johnson_8d
srs_oc_contributed_seawifs_johnson_8d

**Comment by atkinsn** [comment]
> 
> 
> @atkinsn when this is about to be merged, can you modify the robert johnson metadata records so they can point to the new layers names?
> srs_oc_contributed_aqua_johnson_1m
> srs_oc_contributed_seawifs_johnson_1m
> srs_oc_contributed_aqua_johnson_8d
> srs_oc_contributed_seawifs_johnson_8d

Sure, just let me know when

**Comment by lbesnard** [comment]
@atkinsn I would like to tackle this, but this requires some changes on the records. because of the convoluted system with the geoserver cloud deploy release and other stuffs, this probably means that these collections will land in health bad at some stage. which is not a big deal TBH. let's chat

**Comment by atkinsn** [comment]
@lbesnard metadata changes made in readiness

**Pull request merged**
