### PR TITLE
Add additional replacement to marvl.xslt

### PR DESCRIPTION
**Pull request by lwgordonimos**
@julian1 Could you please have a look at this and advise on suitability? This was requested by @smancini to handle an additional scenario where the url attribute has a different name (file_url).

### CODE REVIEW

**Comment by julian1** [comment]
I'm sure the xslt is fine, but why does the attribute not follow convention? Shouldn't it just propagate up from the talend indexing components?

Is it going to cause an issue bodaac?

**Comment by julian1** [comment]
I can't find any instances of file_url as an attribute in the database tables, so presumably it must be in a geoserver view.

**Comment by lwgordonimos** [comment]
@smancini Can you please provide an example of where this is occurring?

**Comment by smancini** [comment]
http://geoserver-123.aodn.org.au/geoserver/imos/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=imos:anmn_velocity_timeseries_map&maxFeatures=50&outputFormat=marvl+xml

**Comment by julian1** [comment]
It looks like the attribute is defined in the view that's created for this harvester.

```
harvest=# \d anmn_velocity.anmn_velocity_timeseries_map
         View "anmn_velocity.anmn_velocity_timeseries_map"
          Column          |            Type             | Modifiers 
--------------------------+-----------------------------+-----------
 timeseries_id            | bigint                      | 
 file_url                 | character varying(512)      | 
 size                     | double precision            | 
 site_code                | text                        | 
 platform_code            | text                        | 
 deployment_code          | text                        | 
 geom                     | geometry(Geometry,4326)     | 
 LATITUDE                 | double precision            | 
 LONGITUDE                | double precision            | 
 instrument_nominal_depth | real                        | 
 time_coverage_start      | timestamp without time zone | 
 time_coverage_end        | timestamp without time zone | 
 time_deployment_start    | timestamp without time zone | 
 time_deployment_end      | timestamp without time zone | 
 instrument               | text                        | 
 instrument_serial_number | text                        | 

harvest=# 
```

Unless there's a strong reason for changing the convention around naming, maybe it would be better to change it here?

**Comment by smancini** [comment]
A few weeks ago, we did some work to have some consistency across layers for geometry but also for time (using time_coverage_start and time_coverage_end).
It was a bit painful but certainly worth it for our MARVL colleague at CSIRO.
Now we have inconsistency with URLs of original files. 
Half of the layers provided to MARVL contains the field "imos:url" and the other half "imos:file_url".

I was hoping that in the short term we could extend the XSLT.
In the medium term, we would try to make these fields consistent across our datasets.

I do not think modifying the XSLT will have any impact on BODAAC.
The portal is already using a different service to provide the list of URLs and ZIP the files. Is it correct?

**Comment by julian1** [comment]
Should this be raised as a backlog item or portal bug to be sorted out?

@jonescc seems to think it will probably be alright..

**Comment by jonescc** [comment]
Sorting out the naming inconsistencies sounds like a content issue to me.

Modifying the MARVL xslt will not affect BODAAC or FileList downloads.

**Comment by julian1** [comment]
@jonescc bears all responsibility!

**Pull request merged**
