### PR TITLE
New layers from moorings metadata harvest

### PR DESCRIPTION
**Pull request by mhidas**
~~DO NOT MERGE~~ until the changes in https://github.com/aodn/harvesters/pull/558 have been merged and deployed.

### CODE REVIEW

**Comment by mhidas** [comment]
Harvester updates have been deployed. Ready to merge.
@xhoenner Would you mind?

**Comment by xhoenner** [comment]
> @xhoenner Would you mind?

I would not, was waiting for you to give me the go ahead on this as I saw the harvester had been promoted to rc but wasn't sure whether it had run.

**Comment by mhidas** [comment]
Thanks for looking out for it. Yes, I've run the harvester so the map views are defined.
I've also promoted the harvester to prod, as it seems to run fine, and doesn't affect anything else.

**Comment by xhoenner** [comment]
All functional, including styles and content.ftl. Nice work @mhidas

**Comment by mhidas** [comment]
@xhoenner Thanks!

**Pull request merged**
