### PR TITLE
delete wms layer that breaks wms getcapabilities

### PR DESCRIPTION
**Pull request by julian1**
There are other exceptions in there, and it takes a long time to compute the first time, but this layer breaks it entirely in my test environment.

### CODE REVIEW

**Comment by julian1** [comment]
https://github.com/aodn/internal-discussions/issues/314

**Comment by pmbohm** [comment]
@lbesnard Can you fix this problem with your own pull request. I will merge this before 5pm if not so that the portals getCapabilities XML is created properly

**Comment by pmbohm** [comment]
https://github.com/aodn/geoserver-config/issues/415

**Comment by lbesnard** [comment]
.... And so ? we delete the layer, and it's fixed ? what's next ? Is there a plan to investigate further ?

**Comment by pmbohm** [comment]
The cause was investigated and points to the bug #415
aus_phyto_db_ongoing_data layer has problems that breaks GetCapabilities XML

**Comment by lbesnard** [comment]
I read it and can't really understand what it is about. My point is that the only solution was to delete the layer while it has been there for a few weeks. And there is no plan to know who is going to have a look at this. 

@smancini @pblain

**Comment by julian1** [comment]
@lbesnard https://github.com/aodn/backlog/issues/465

**Comment by lbesnard** [comment]
So I did a bit of investigation on my pobox, with the layer on.

Verdict, not a single problem at getting the get capabilities.
Catalina.out doesn't show anything wrong.

Both following queries to look for bad geometries which could have created issues return 0 row
```sql
SELECT * from aus_phyto_db_ongoing.aus_phyto_db_data where  st_isvalid(geom) is false;
SELECT * from aus_phyto_db_ongoing.aus_phyto_db_mapwhere  st_isvalid(geom) is false;
```

AFAIK there is no issue with the layer.

@pblain @smancini

**Comment by julian1** [comment]
Hi @lbesnard 

I restored the deleted layer on production so that GetCapabilities is broken again. Here is the exception in the log,

```
Caused by: javax.xml.transform.TransformerException: org.geoserver.platform.ServiceException: Error occurred trying to write o
ut metadata for layer: aus_phyto_db_ongoing_data
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:755)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:359)
        at org.geotools.xml.transform.TransformerBase$Task.run(TransformerBase.java:300)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:133)
        at org.geotools.xml.transform.TransformerBase.transform(TransformerBase.java:112)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Response.write(Capabilities_1_3_0_Response.java:48)
        ... 89 more
Caused by: org.geoserver.platform.ServiceException: Error occurred trying to write out metadata for layer: aus_phyto_db_ongoin
g_data
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.doHandleLayer(Capabilit
ies_1_3_0_Transformer.java:884)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayerTree(Capabil
ities_1_3_0_Transformer.java:837)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayers(Capabiliti
es_1_3_0_Transformer.java:717)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleCapability(Capabi
lities_1_3_0_Transformer.java:465)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.encode(Capabilities_1_3
_0_Transformer.java:273)
        at org.geotools.xml.transform.TransformerBase$XMLReaderSupport.parse(TransformerBase.java:1026)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transformIdentity(TransformerImpl.java:677)
        at com.sun.org.apache.xalan.internal.xsltc.trax.TransformerImpl.transform(TransformerImpl.java:746)
        ... 94 more
Caused by: java.lang.NullPointerException: Layer aus_phyto_db_ongoing_data has no default style
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleStyles(Capabiliti
es_1_3_0_Transformer.java:1031)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.handleLayer(Capabilities_1_3_0_Transformer.java:979)
        at org.geoserver.wms.capabilities.Capabilities_1_3_0_Transformer$Capabilities_1_3_0_Translator.doHandleLayer(Capabilities_1_3_0_Transformer.java:877)
        ... 101 more
```

I'll leave it to @pblain and @smancini to decide how they want to proceed.

**Comment by jonescc** [comment]
@lbesnard - l think the relevant bit of the log above is:

Layer aus_phyto_db_ongoing_data has no default style

So looks like a similar issue to the previous ones.

**Comment by jonescc** [comment]
On production:

```
craigj@1-aws-syd:/mnt/ebs/geoserver_123$ grep -ir 28ae9436:15722231f36 .
./workspaces/imos/JNDI_aus_phyto_ongoing/aus_phyto_db_ongoing_data/layer.xml:    <id>StyleInfoImpl--28ae9436:15722231f36:-7ffb</id>
```

So looks like this layer sets the default style as StyleInfoImpl--28ae9436:15722231f36:-7ffb but this is not defined anywhere in styles.

HTH

**Comment by jonescc** [comment]
Perhaps a missing checkin?

**Comment by julian1** [comment]
Apparently @lbesnard is not in today. I don't think we can leave this broken over the weekend.

**Comment by julian1** [comment]
https://github.com/aodn/geoserver-config/pull/419

**Pull request merged**
