### PR TITLE
SOOP ASF FMT - rename old schema *_MFT to *_FMT with appropriate view…

### PR DESCRIPTION
**Pull request by lbesnard**
…s and tables

### CODE REVIEW

**Comment by danfruehauf** [comment]
All data was loaded.

@atkinsn Can you please update corresponding metadata? It's a simple search and replace:
 * `soop_asf_mft_trajectory_data` -> `soop_asf_fmt_trajectory_data`
 * `soop_asf_mft_trajectory_map` -> `soop_asf_fmt_trajectory_map`

@lbesnard Please amend to that if it's not all that you want modified.

Thanks!

**Comment by atkinsn** [comment]
I have updated the corresponding metadata record - wms, wfs and bodaac links.

**Comment by danfruehauf** [comment]
@atkinsn Thanks.

@lbesnard Did you merge this to production branch?

**Comment by lbesnard** [comment]
@danfruehauf  yeap done

**Pull request merged**
