### PR TITLE
WPS - add template for RAMSSA GAMSSA sat product; Rename ghrsst l3* t…

### PR DESCRIPTION
**Pull request by lbesnard**
…emplate

### CODE REVIEW

**Comment by jonescc** [comment]
Require changes on https://github.com/aodn/geoserver-config/tree/gamssa-ramssa

**Comment by lbesnard** [comment]
@jonescc which changes ?

**Comment by jonescc** [comment]
https://github.com/aodn/geoserver-config/pull/564 - your original RAMSSA/GAMSSA changes were reverted in master and added here so that we could deploy other changes to production.

**Comment by lbesnard** [comment]
@jonescc after a year-long wait, could we merge this PR, please?

**Comment by jonescc** [comment]
Hi Loz,  we had an aws-wps integration test failure after merging these changes yesterday:

[ERROR] Failures: 
[ERROR]   ExecuteIT.testSrsSubset:289 
Expected: an XML document with XPath /netcdf/attribute[@name='start_time']/@value "2017-10-19T03:20:00Z"
     but: was "20171018T185545Z"
[INFO] 

Seems to imply the formatting of start_time has changed for aggregations for  srs_ghrsst_l3s_1d_day_url which we use in our test.    Not sure if this is a problem.

**Comment by lbesnard** [comment]
@jonescc I don't really understand how those changes would break the tests. On which product/files is this failing?

**Comment by jonescc** [comment]
OK, so before the changes we were matching a template with start time etc specified:

    Template match: Layer [srs_ghrsst_l3s_1d_day_url], Template Name [srs_ghrsst], Match [srs_ghrsst.*,srs_sst.*]

After the changes, we are matching the default template:

    Template match: Layer [srs_ghrsst_l3s_1d_day_url], Template Name [default], Match [.*]

We may be using an old collection name 'srs_ghrsst_l3s_1d_day_url' for testing?  If so, that's fine, we  just need to adjust our tests.

**Pull request merged**
