### PR TITLE
Fix anmn_am_nrt layers

### PR DESCRIPTION
**Pull request by mhidas**
Fixes https://github.com/aodn/issues/issues/705

The `anmn_am_nrt_data` layer has a configuration issue which has made it disappear from geoserver. This should fix it.
Also a bit of cleaning up:
* added missing content.ftl to the corresponding `_map` layer;
* deleted the obsolete layers from the old `anmn_am_nrt` schema.

### CODE REVIEW

**Comment by pmbohm** [comment]
@mhidas Looks good.  Less confusing for humans and machines. The config.ftl is not in the map layer folder which probably still works, but was that intended?

**Comment by mhidas** [comment]
> The config.ftl is not in the map layer folder which probably still works, but was that intended?

Yes. Pretty sure if it doesn't find it in the layer's own folder, it just works its way up the directory tree until it finds it. This way the same content.ftl is shared between the dm and nrt map layers, which makes sense.

**Comment by mhidas** [comment]
I did test them both in the stack geoserver layer preview, and they worked fine, including the fetFeatureInfo (i.e. content.ftl works ok)

**Comment by mhidas** [comment]
@pmbohm Please merge this if you're happy with it. It would be great to get it in before the geoserver prod deployment -- or whatever it is that needs to happen for this to get into the portal so the layer is no longer in bad health.

**Comment by mhidas** [comment]
@aodn/devops Would someone mind reloading the config on **geoserver-rc** so that I can test this change?

**Comment by mhidas** [comment]
Thanks. The changes are now on geoerver-rc as expected.

**Comment by lwgordonimos** [comment]
Sorry meant to drop a comment in last night. I cooked the node and confirmed Tomcat had restarted, and spot checked the layers.

**Pull request merged**
