### PR TITLE
 marvl3 getfeature info : swap opened brackets with closed brackets i…

### PR DESCRIPTION
**Pull request by bpasquer**
…n content ftl

### CODE REVIEW

**Comment by bpasquer** [comment]
@lbesnard , @ggalibert , @xhoenner . Rog found this bug this morning. It'll take a minute to review. thanks

**Comment by danfruehauf** [comment]
In order to deploy that to prod, you need to trigger on jenkins the `geoserver_prod_merge` job:
https://jenkins.aodn.org.au/view/geoserver_config_prod_merge/job/geoserver_config_prod_merge_trigger/

To RC it should deploy automatically (and it does now).

**Comment by ggalibert** [comment]
Deployed to production. @bpasquer can you please check?

**Comment by bpasquer** [comment]
yes ,
thanks
On 3 Feb 2016, at 12:16 PM, Guillaume Galibert <notifications@github.com<mailto:notifications@github.com>> wrote:


Deployed to production. @bpasquer<https://github.com/bpasquer> can you please check?

—
Reply to this email directly or view it on GitHub<https://github.com/aodn/geoserver-config/pull/323#issuecomment-178937507>.

Dr. Benedicte Pasquer
Project Officer, e-Marine Information Infrastructure, IMOS
Monday - Friday 9am -3pm
University of Tasmania, Private Bag 110, Hobart, Tasmania, 7001, Australia
Ph: +61 3 6226 1927















University of Tasmania Electronic Communications Policy (December, 2014).
This email is confidential, and is for the intended recipient only. Access, disclosure, copying, distribution, or reliance on any of it by anyone outside the intended recipient organisation is prohibited and may be a criminal offence. Please delete if obtained in error and email confirmation to the sender. The views expressed in this email are not necessarily the views of the University of Tasmania, unless clearly intended otherwise.

**Comment by danfruehauf** [comment]
> Deployed to production. @bpasquer can you please check?

Let it naturally deploy at 17:00, unless you really want that geoserver restart now...

**Comment by bpasquer** [comment]
Ok no worries, It can wait a few hours, 
Thanks guys

**Pull request merged**
