### PR TITLE
add_four_new_layers

### PR DESCRIPTION
**Pull request by ana-berger**
layers in this commit:
- dwm_sofs_surfaceprop_rt_data
- dwm_sofs_surfaceprop_rt_map
- dwm_ts_timeseries_data
- dwm_ts_timeseries_map

Ten more to come

### CODE REVIEW

**Comment by lwgordonimos** [comment]
Just noticed a few files managed to sneak through that shouldn't be in the PR. It's not ideal at the moment, having to manually exclude things that aren't related to layers, but it's quite difficult to only collect relevant changes out of a bunch of changed files!

Every file that's *not* underneath `workspaces/imos` should be excluded here, as they are files either created from a template during deployment, or Geoserver has automatically created them when it started up. Either way, they're not a change that we would want to promote to RC/production from a dev stack.

**Comment by ana-berger** [comment]
yes @lwgordonimos, I totally understand, very sorry about that. Is the first time I am working with the Geoserver layers so probably I messed up a bit. This PR still needs to wait for more changes, more layers to be created. I will make sure I fix it and delete the unwanted files before the merge. Thanks for explaining it

**Comment by ana-berger** [comment]
I will create a new PR and close this one. Please ignore it

**Comment by lwgordonimos** [comment]
> very sorry about that

Not at all, I'm apologising to *you* because it's a pain in the neck for POs, particularly new ones! ;) Just thought I'd note it while I noticed it.

**Pull request closed without merging**
