### PR TITLE
SOOP TMV NRT - add default style to WFS

### PR DESCRIPTION
**Pull request by lbesnard**

### CODE REVIEW

**Comment by lbesnard** [comment]
in ref to issue https://github.com/aodn/content/issues/408

I added the generic style to the WFS (as mentioned by @jonescc )via the geoserver gui. However, seeing the changes this did on the file, it doesn't inspire me with much confidence on the life purpose of this PR.

Also since this issue can't be seen on RC, and only on geoserver-portal, I don't think it makes much sense to wait for the next release only to find out it didn't work @ccmoloney?

**Comment by jonescc** [comment]
Yep - that doesn't look like it will help.  I'll have a look at what's happening in prod versus rc.  

I think we want the 'testing' environment to be as close to prod as possible so you don't get different results.

**Comment by jonescc** [comment]
Looks like there is a problem rendering the getcapabilities section for this layer in rc as well.  Where are you making these modifications?   I suspect the id of the default style there is different to whats in geoserver_config.

**Comment by jonescc** [comment]
Or the style you've referenced hasn't been included in your changes.

**Comment by lwgordonimos** [comment]
I ran it through the patented Official AODN Geoserver Config Validation Utility (https://github.com/aodn/utilities/pull/60) and sure enough:

```
imos:soop_tmv_nrt_trajectory_data - status='INVALID' reason='references nonexistent style: StyleInfoImpl--5aad8138:161b5a7f073:-7ffc'
```

Was thinking it would be good to get that script ship shape and we can add it as a pre-commit (even travis or something) thing to make sure that styles at least are correct before committing.

**Comment by jonescc** [comment]
I think travis is the ideal place for it.  That way when the pr is created, the po's will get a message saying the style doesn't exist.

**Comment by lwgordonimos** [comment]
I turned off the check for missing styles, because it not as clear cut whether this is even a problem in some cases, but the ones which reference a non-existent style are definitely a problem. Before adding to travis, we'd need to fix these first:

```
02:41:58 {geoserver-config-validate} ~/git/aodn/utilities/geoserver/config_validator$ python validate_geoserver_config.py ../../../geoserver-config/
VALID LAYERS COUNT: 323
INVALID LAYERS COUNT: 5
INVALID LAYERS:
imos:csiro_cars_monthly_url - status='INVALID' reason='references nonexistent style: StyleInfoImpl--396ecd48:155a40f3d82:-7ffc'
imos:srs_ghrsst_l3s_1d_day_url - status='INVALID' reason='references nonexistent style: StyleInfoImpl--28ae9436:15722231f36:-7ffb'
imos:soop_tmv_nrt_trajectory_data - status='INVALID' reason='references nonexistent style: StyleInfoImpl--5aad8138:161b5a7f073:-7ffc'
imos:csiro_cars_weekly_url - status='INVALID' reason='references nonexistent style: StyleInfoImpl--396ecd48:155a40f3d82:-7ffc'
imos:aodn_uwa_glider_trajectory_data - status='INVALID' reason='references nonexistent style: StyleInfoImpl-5aa01124:15233403c30:-7ffc'
```

**Comment by lbesnard** [comment]
just changed the default style. Maybe it work, maybe it won't !

**Comment by lbesnard** [comment]
@lwgordonimos so what are the next steps from here ? do we wait for the next release ?

**Comment by ccmoloney** [comment]
@lbesnard At the moment do what you would usually do - if you would usually get a fix released to prod, then do that.  The whole idea of promoting these things as part of a release is to get them tested properly before they go to production - but we aren't there yet.

**Pull request merged**
