### PR TITLE
Publish layers for MARVL, ONLY MERGE TO MASTER

### PR DESCRIPTION
**Pull request by xhoenner**
Can someone review that ASAP as these layers will be needed for a meeting with Rog on Monday?

### CODE REVIEW

**Comment by ggalibert** [comment]
On it

**Comment by ggalibert** [comment]
-When clicking on the OpenLayers link of asset_map a window asks me to save something rather than displaying the wms layer:
screenshot from 2015-01-30 14 30 35
-OpenLayer link for csiro_data takes ~10sec before displaying anything.
-OpenLayer link for wod_data took more than a minute before displaying anything.
-No content FTL set up.

**Comment by ggalibert** [comment]
In addition, I can't find any of these layers in the WMS 1.1.1 getCapabilities result. Is this normal?

**Comment by xhoenner** [comment]
Thanks @ggalibert for reviewing that.
The asset_map shouldn't have been part of that commit, I removed this layer.
No content.ftl set up as it's not for publication purposes but just to show those layers to Rog.
Yes, both csiro and wod layers take a while to load up as there are respectively over 90 000 and 500 000 rows.

**Comment by ggalibert** [comment]
DO NOT MERGE TO PROD

**Pull request merged**
