### PR TITLE
Create new layers for GPS data for hawksbill turtles + modify style

### PR DESCRIPTION
**Pull request by xhoenner**

### CODE REVIEW

**Comment by lbesnard** [comment]
@xhoenner I'll review tomorrow once harvester will have ran tonight on prod. please remind me

**Comment by xhoenner** [comment]
Will do, thanks @lbesnard

**Comment by xhoenner** [comment]
@lbesnard there doesn't seem to be any issue with the harvester, can you review this PR then please?

**Comment by lbesnard** [comment]
looks good to me, haven't tested against portal though

**Comment by lbesnard** [comment]
@xhoenner you can merge to prod

**Comment by xhoenner** [comment]
just done that, thanks for reviewing that PR @lbesnard

**Pull request merged**
