### PR TITLE
Set maxRenderingTime for any WMS request

### PR DESCRIPTION
**Pull request by pmbohm**
https://docs.geoserver.org/stable/en/user/services/wms/configuration.html#wms-configuration-limits

### CODE REVIEW

**Comment by pmbohm** [comment]
For https://github.com/aodn/backlog/issues/821

**Comment by pmbohm** [comment]
Max rendering times for NOAA drifters was 1.8 seconds @APaulic 

Screen Shot 2020-02-24 at 12 30 12 pm
Screen Shot 2020-02-24 at 12 29 45 pm

**Comment by pmbohm** [comment]
@APaulic 40s is high enough to not interfere with noaa_drifter rendering. 
But as errors still occur is it worth introducing?

**Comment by pmbohm** [comment]
@APaulic  https://geoserver.geo-solutions.it/edu/en/adv_gsconfig/parameters.html#geoserver-parameters
Default `maxRenderingTime` is  60 seconds

**Comment by APaulic** [comment]
:thinking: the default might be 60 but I still think some of our layers, such as ARGO, may be out of the normal operating parameters for GeoServer. 

In regards to the errors still occurring, I assume that this is during a simulated portal loading scenario rather than a stress test and if so what errors are occurring. If the portal can't get generated tiles under normal operation I'd say its a no go. Perhaps a good test is to use the full stack and click around on portal and see if any tile fails to render. 

Also, when you say rendering does this include the seeding process? The 80+ second response would break both these limits.

If seeding is somehow whitelisted with these restrictions and we can load something like the noaa_drifter without skimming the edge of the limit I think it's fine to continue to the systest where ARGO will determine its suitability.

**Comment by pmbohm** [comment]
@APaulic The value was previously unlimited! Anyhow now i'm leaving it alone

**Pull request merged**
